package section6;

/**
 * DECLARE A long VARIABLE THAT HOLDS A VERY LARGE VALUE, PROBABLY IN THE
 * BILLIONS. PRINT THIS LONG VALUE TO THE CONSOLE. ASSIGN THIS LONG VALUE TO AN
 * int VARIABLE AND NOTICE THE COMPILER ERROR. FIX THE ERROR (HINT:CASTING)
 * PRINT THE INT VALUE AND COMPARE IT WITH ITS LONG COUNTERPART
 */
public class Exercise2 {

	public static void main(String[] args) {

	}

}
